import type { NextPage } from 'next'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import { useCallback, useEffect, useState } from 'react'
import styles from '../styles/Home.module.scss'
import { supabase } from '../utils/supabaseClient'
import ProductComponent from '../components/ProductComponent'
import Search from '../components/Search'
import { Product } from '../types'
import { GiFullPizza, GiCookie } from 'react-icons/gi'
import { MdCake } from 'react-icons/md'

type Props = {
  children: React.ReactNode,
  data: Product[] | [],
  categories: string[],
}

const Home: NextPage<Props> = ({data, categories}) => {
  const [products, setProducts] = useState<any[]>([])
  const [selectedCategory, setSelectedCategory] = useState<string>('')

  const categoryList = [
    {
      name: 'Пицца',
      icon: <GiFullPizza size={22} color='#f0be62' />,
    },
    {
      name: 'Десерты',
      icon: <GiCookie size={22} color='#b38c24' />,
    },
    {
      name: 'Пироги',
      icon: <MdCake size={22} color='#f7aefa' />,
    },
  ]

  const filterProducts = useCallback((category: string) => {
    setSelectedCategory(category)
    setProducts(data.filter(product => product.category === category))
  }, [data])

  useEffect(() => filterProducts(categories[0]), [categories, filterProducts])

  return (
    <main className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Search products={data} />

      <div className='spacer'></div>

      <div className={styles.top_menu}>
        <div className={styles.categories_container}>
          {categoryList.map(category => 
            <div
              key={category.name}
              onClick={() => filterProducts(category.name)}
              className={selectedCategory === category.name ? styles.button + ' ' + styles.active : styles.button}
            >
              <span>{category.name}</span>
              {category.icon}
            </div>)
          }
        </div>
      </div>

      <div className={styles.main}>
          {products.map(product => <ProductComponent key={product.id} product={product} />)}
      </div>

    </main>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const { data, status, error } = await supabase.from('products').select('id, title, price, name, category, image')

  const categories = data && Array.from(new Set(data.map(product => product.category)))
  
  if (error && status !== 406) throw error

  return {
    props: {
      data: data ? data : [],
      categories,
    },
  }
}

export default Home
